#MAILTO="jinyuan@baidu.com,zhangxiaonan@baidu.com"
MAILTO="jinyuan@baidu.com"
0 0 * * * python /home/ubuntu/newsman/newsman/watchdog/cleaner.py data
10 0,8,16 * * * python /home/ubuntu/newsman/newsman/watchdog/cleaner.py zombie
20 0 * * * python /home/ubuntu/newsman/newsman/watchdog/idler.py
# 0 * * * * python /home/ubuntu/newsman/newsman/watchdog/analyzer.py en
# 10 * * * * python /home/ubuntu/newsman/newsman/watchdog/analyzer.py th
# 20 * * * * python /home/ubuntu/newsman/newsman/watchdog/analyzer.py ind
# 30 * * * * python /home/ubuntu/newsman/newsman/watchdog/analyzer.py en-rIN
# 40 * * * * python /home/ubuntu/newsman/newsman/watchdog/analyzer.py ja
# 50 * * * * python /home/ubuntu/newsman/newsman/watchdog/analyzer.py pt
